version: 0.2

phases:
  install:
    commands:
        - apt-get update
        - apt-get install -y curl
        - apt-get install python3-venv
        - python3 -m venv venv
        - source venv/bin/activate
        - pip install Flask
    finally:
        - echo Preliminary tasks done
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python3 test_app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - web.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
